@URL=http://localhost:5000/
@USER_ID=481925087

###
GET {{URL}}


###
GET {{URL}}/users

###
POST {{URL}}/users
Content-Type: application/json

{
    "email": "victor.cyprien@limayrac.fr",
    "name": "Victor CYPRIEN",
    "password": "password",
    "user_id": 123
}


###
GET {{URL}}/users/{{USER_ID}}


###
PUT {{URL}}/users/{{USER_ID}}
Content-Type: application/json

{
    "email": "victor.cyprien@limayrac.fr",
    "name": "Victor CYPRIEN",
    "password": "password"
}


###
DELETE {{URL}}/users/{{USER_ID}}
Content-Type: application/json
